language: python

python:
  - 3.6

services: postgresql

#commands to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database questioner;' -U postgres
  - python manage.py syncdb --noinput

#command to run the test suite
script:
  - python manage.py test

after_success:
  - coveralls


