language: python

python:
  - "3.6"

services:
  - postgresql

env:
  global:
    -
  matrix:
    - DB=postgresql

before_script:
  - psql -c 'create database travis_ci_db;' -U postgres

install:
  - pip install -r requirements.txt

script:
  - py.test

after_success:
  - coveralls
