language: python

python:
  - "3.6"

services:
  - postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="questioner.travis_ci_settings"
    # - PYTHONPATH="/home/travis/build/AtamaZack/questioner"
    # - PIP_USE_MIRRORS=true
  # matrix:
    # - Django==2.0.13 DB=postgresql

before_script:
  - psql -c 'create database travis_ci_db;' -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test questioner
  - python -m pytest --cov

after_success:
  - coveralls
