language: python

python:
  - "3.6"

services:
  - postgresql

env:
  global:
    - PYTHONPATH="/home/travis/build/PatrickMugayaJoel/questioner"
    - PIP_USE_MIRRORS=true
  matrix:
    - Django==2.0.13 DB=postgresql

install:
  - pip install -r requirements.txt

script:
  - py.test

after_success:
  - coveralls
