language: python

python:
  - "3.6"

services:
  - postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="questioner.settings"
    - PYTHONPATH="/home/travis/build/PatrickMugayaJoel/questioner"
    - PIP_USE_MIRRORS=true
  matrix:
    - Django==2.0.13 DB=postgresql

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test questioner
  - python -m pytest --cov

after_success:
  - coveralls
