language: python

python:
  - 3.6

addons:
  postgresql: "9.6"

#commands to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database questioner;' -U postgres

script:
  - python manage.py test
  - python manage.py makemigrations
  - python manage.py migrate

after_success:
  - coveralls
